site_name: Xrnt's blog

nav:
- Home: index.md
- CTF:  
  - Java: 
    - Fastjson: CTF/Web/Java/Fastjson反序列化.md
    - Java反序列化: CTF/Web/Java/Java反序列化.md
  - Web基础:
    - Header头: CTF/Web/Web基础/Header头.md
  - 网安Web培训: 
    - CTF/Web/网安Web培训/http+python基础+python抓包发包2.md
    - CTF/Web/网安Web培训/命令执行.md
    - CTF/Web/网安Web培训/命令执行进阶.md
- Writeup : 
  - Web: Writeup/Web.md
- Python:
  - Python数据容器: python/2_Python数据容器.md
- About: about.md

theme:
  name: material
  palette: 
 
    # Palette toggle for light mode
    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
 
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features: 
    - navigation.instant #- header.autohide  #自动隐藏
    #- announce.dismiss #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
    - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    #- navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    #- navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - navigation.expand # 打开Tab时左侧目录全部展开
    #- navigation.indexes #启用节索引页后，可以将文档直接附加到节
    - search.share #搜索分享按钮
  language: zh # 一些提示性的文字会变成中文
  icon: 
    repo: fontawesome/brands/github #右上角图标
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
      
edit_uri: edit/main/docs # 编辑按钮跳转的链接 
repo_url: https://github.com/xrntkk/xrntkk.github.io # 右上角点击跳转的链接
repo_name: xrntkk.github.io # 右上角的名字


markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  - md_in_html
  - meta # 支持Markdown文件上方自定义标题标签等
  - pymdownx.caret
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format # 代码块高亮插件
  - pymdownx.arithmatex:  # latex支持
      generic: true
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
      auto_title: true # 显示编程语言名称
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
 
      

plugins:
  - search
  - tags:
      tags_file: tag.md  #分类标签
  - blog


extra_javascript:
  - javascripts/extra.js


extra_css:
  - stylesheets/extra.css # 自定义CSS


